# Generated by Django 6.1 on 2026-08-31 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('default_rehearsal_duration_minutes', models.PositiveIntegerField()),
                ('default_setup_grace_minutes', models.PositiveIntegerField()),
                ('default_teardown_grace_minutes', models.PositiveIntegerField()),
                ('default_song_slot_count', models.PositiveIntegerField()),
            ],
        ),
    ]
