# Generated by Django 6.1 on 2026-08-31 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_membership_membershiprole_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('length', models.DurationField()),
                ('notes', models.TextField(blank=True)),
                ('position', models.PositiveIntegerField()),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.semester')),
            ],
            options={
                'ordering': ['semester', 'position'],
                'constraints': [models.UniqueConstraint(deferrable=models.Deferrable.DEFERRED, fields=('semester', 'position'), name='unique_song_position_per_semester')],
            },
        ),
    ]
