# Generated by Django 6.1 on 2026-08-31 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_song'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongRoleRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.role')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.song')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('song', 'role'), name='unique_role_requirement_per_song')],
            },
        ),
    ]
