# Generated by Django 6.1 on 2026-08-31 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_song'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rehearsal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('setup_grace_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('teardown_grace_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('is_full_setlist', models.BooleanField(default=False)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.semester')),
            ],
            options={
                'ordering': ['semester', 'date', 'start_time'],
            },
        ),
    ]
