# Generated by Django 6.1 on 2026-08-31 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_songrolerequirement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SongRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_role_mismatch', models.BooleanField(default=False)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.role')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.song')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('song', 'role', 'person'), name='unique_song_role_person')],
            },
        ),
    ]
