# Generated by Django 6.1 on 2026-08-31 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_rehearsal'),
    ]

    operations = [
        migrations.CreateModel(
            name='RehearsalSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('slot_count', models.PositiveIntegerField(default=1)),
                ('start_time', models.TimeField(editable=False)),
                ('end_time', models.TimeField(editable=False)),
                ('rehearsal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.rehearsal')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.song')),
            ],
            options={
                'ordering': ['rehearsal', 'order'],
                'constraints': [models.UniqueConstraint(fields=('rehearsal', 'order'), name='unique_order_per_rehearsal')],
            },
        ),
    ]
