# Generated by Django 6.1 on 2026-08-31 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0008_alter_rehearsalsong_slot_count_recording'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='file',
            field=models.FileField(unique=True, upload_to='recordings/'),
        ),
    ]
