# Generated by Django 6.1 on 2026-08-31 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0008_alter_rehearsalsong_slot_count_recording'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('full_conflict', 'Full conflict'), ('partial', 'Partial')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rehearsal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.rehearsal')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('person', 'rehearsal'), name='unique_conflict_per_person_per_rehearsal')],
            },
        ),
    ]
