# Generated by Django 6.1 on 2026-08-31 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0009_conflict'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConflictWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unavailable_start', models.TimeField()),
                ('unavailable_end', models.TimeField()),
                ('conflict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.conflict')),
            ],
        ),
    ]
