# Generated by Django 6.1 on 2026-09-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0011_alter_recording_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='conflict',
            name='reason',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
