# Generated by Django 6.1 on 2026-09-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0011_alter_recording_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='rehearsal',
            name='arrival_buffer_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rehearsal',
            name='departure_buffer_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='default_arrival_buffer_minutes',
            field=models.PositiveIntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='semester',
            name='default_departure_buffer_minutes',
            field=models.PositiveIntegerField(default=5),
            preserve_default=False,
        ),
    ]
