# Generated by Django 6.1 on 2026-09-03 02:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0015_semester_lifecycle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_role_mismatch', models.BooleanField(default=False)),
                ('covering_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups_covered_for', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rehearsal_song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.rehearsalsong')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.role')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('rehearsal_song', 'role', 'person'), name='unique_backup_per_slot_role_person'), models.CheckConstraint(condition=models.Q(('person', models.F('covering_for')), _negated=True), name='backup_person_is_not_covering_for_self')],
            },
        ),
    ]
