# Generated by Django 6.1 on 2026-09-03 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0015_semester_lifecycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='conflict',
            name='adjudication_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='conflict',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
