# Generated by Django 6.1 on 2026-09-03 03:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0016_backup'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
