# Generated by Django 6.1 on 2026-09-03 03:11

import django.core.validators
from django.db import migrations, models


def delete_zero_count_requirements(apps, schema_editor):
    """Delete any pre-existing zero-count SongRoleRequirement rows.

    Nothing in the app creates one today, but the incoming check constraint
    (issue #206) can't apply over data that violates it. A zero-count
    Requirement asserts nothing and is indistinguishable from the Role not
    being required at all, so deleting it is the honest cleanup rather than
    bumping it to some arbitrary nonzero count.
    """
    SongRoleRequirement = apps.get_model('scheduling', 'SongRoleRequirement')
    SongRoleRequirement.objects.filter(count=0).delete()


def noop_reverse(apps, schema_editor):
    """Irreversible: the deleted zero-count rows can't be reconstructed."""


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0016_backup'),
    ]

    operations = [
        migrations.RunPython(delete_zero_count_requirements, noop_reverse),
        migrations.AlterField(
            model_name='songrolerequirement',
            name='count',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddConstraint(
            model_name='songrolerequirement',
            constraint=models.CheckConstraint(condition=models.Q(('count__gte', 1)), name='role_requirement_count_at_least_one'),
        ),
    ]
