# Generated by Django 6.1 on 2026-09-03 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0020_rehearsal_unique_date_per_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='default_dress_rehearsal_count',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.CreateModel(
            name='RehearsalPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('semester', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scheduling.semester')),
            ],
        ),
        migrations.CreateModel(
            name='RehearsalTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rehearsal_times', to='scheduling.rehearsalpattern')),
            ],
            options={
                'ordering': ['pattern', 'day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='SkipDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skip_dates', to='scheduling.rehearsalpattern')),
            ],
        ),
    ]
