# Generated by Django 6.1 on 2026-09-06 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_authemailrequest_loginattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='invited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
