# Generated by Django 6.1 on 2026-09-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_person_invited_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
    ]
