# Generated by Django 6.1 on 2026-09-12 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0005_remove_email_invite_flow'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='theme_preference',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='system', max_length=10),
        ),
    ]
